# Using multi-stage approach
# Build JAR file
FROM maven:3.9.9-eclipse-temurin-11 AS builder
WORKDIR /app
# Copies pom.xml and code to /app in the container
COPY . .
# Builds JAR, add -DskipTests after "package" for faster build times
RUN mvn clean package -DskipTests

# Pull JAR into a clean environment and run
FROM openjdk:11
WORKDIR /app
# Copy the JAR file from the builder stage to the current stage
# JAR file will be located in /target directory after build
COPY --from=builder /app/target/*-jar-with-dependencies.jar client-service.jar
# Run the service
# ENTRYPOINT [ - , - , - , args[0], args[1], args[2], args[3]]
ENTRYPOINT ["java", "-jar", "client-service.jar", "0.6", "100", "true"]